[package]
name = "spnl-wasm"
version = "0.3.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
serde_json = "1.0.140"
spnl = { version = ">=0.1.0", path = "../../spnl", default-features = false, features = ["run","yaml"] }
wasm-bindgen = "0.2.100"
