[package]
name = "spnl"
version = "0.1.0"
edition = "2024"

[features]
default = ["run", "ollama", "openai", "pull"]
run = ["dep:futures","dep:indicatif","dep:async-recursion","dep:rustyline","dep:tokio","dep:tokio-stream"]
ollama = ["run","dep:ollama-rs"]
openai = ["run","dep:async-openai"]
pull = ["dep:duct","dep:fs4","dep:rayon"]

[dependencies]
ptree = { version = "0.5.2", default-features = false, features = ["ansi"] }
serde = "1.0.219"
serde-lexpr = "0.1.3"
async-openai = { version = "0.28.1", optional = true }
async-recursion = {version = "1.1.1", optional = true }
duct = { version = "0.13.7", optional = true }
fs4 = { version = "0.13.1", optional = true }
futures = { version = "0.3.31", optional = true }
indicatif = { version = "0.17.11", features = ["rayon"], optional = true }
ollama-rs = { version = "0.3.1", features = ["stream"], optional = true }
rayon = { version = "1.10.0", optional = true }
rustyline = { version = "15.0.0", features = ["with-file-history"], optional = true } 
tokio = { version = "1.44.1", features = ["io-std"], optional = true }
tokio-stream = { version = "0.1.17", optional = true }
