name: core

on:
  push:
    branches: [ main, checkingOSRunner ]
  pull_request:
    branches: [ main ]

# cancel any prior runs for this workflow and this PR (or branch)
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  
env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: core
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          # - windows-latest
          - macos-latest
    steps:
      - uses: actions/checkout@v5

      - name: download rust-cache
        run: |
          mkdir rust-cache-action && cd rust-cache-action
          mkdir -p dist/save
          (cd dist/save && wget https://raw.githubusercontent.com/Swatinem/rust-cache/refs/heads/master/dist/save/index.js)
          mkdir -p dist/restore
          (cd dist/restore && wget https://raw.githubusercontent.com/Swatinem/rust-cache/refs/heads/master/dist/restore/index.js)
          wget https://raw.githubusercontent.com/Swatinem/rust-cache/refs/heads/master/action.yml
      - uses: ./rust-cache-action

      - name: Setup protoc
        run: |
          if [ $RUNNER_OS = "Linux" ]
          then
            if [ $RUNNER_ARCH = "X64" ]
            then arch=x86_64
            elif [ $RUNNER_ARCH = "ARM64" ]
            then arch=aarch_64
            else
              echo "Unsupported arch for protoc"
              exit 1
            fi
            curl -L -o protoc.zip https://github.com/protocolbuffers/protobuf/releases/download/v31.1/protoc-31.1-linux-$arch.zip
          elif [ $RUNNER_OS = "macOS" ]
          then curl -L -o protoc.zip https://github.com/protocolbuffers/protobuf/releases/download/v31.1/protoc-31.1-osx-universal_binary.zip
          fi
          unzip protoc.zip -d $HOME/.local
      # - uses: Swatinem/rust-cache@v2
      # - uses: pydantic/ollama-action@v3

      - name: report cargo version
        run: cargo --version

      - name: report rustc version
        run: rustc --version

      - name: install ollama
        run: |
          if [ "$RUNNER_OS" = "Linux" ]; then
            curl -fsSL https://ollama.com/install.sh | sudo -E sh
            sleep 2
            ollama serve &
          elif [ "$RUNNER_OS" = "macOS" ]; then
            if ! command -v brew &> /dev/null
            then
                echo "Homebrew not found. Installing Homebrew..."
                /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
                if [ -f "/opt/homebrew/bin/brew" ]; then
                    eval "$(/opt/homebrew/bin/brew shellenv)"
                elif [ -f "/usr/local/bin/brew" ]; then
                    eval "$(/usr/local/bin/brew shellenv)"
                fi
                echo "Homebrew installed."
            else
                echo "Homebrew is already installed. Updating..."
                brew update
            fi

            echo "Installing Ollama..."
            brew install ollama
            echo "Starting Ollama server as a background service..."
            brew services start ollama

            sleep 5
            echo "Ollama installed and server started."

            echo "Verifying server status..."
            if curl -s http://localhost:11434/ | grep -q "Ollama is running"; then
                echo "✅ Ollama server is running successfully."
                echo ""
                echo "To run your first model (e.g., Llama 3), use:"
                echo "ollama run llama3"
            else
                echo "❌ Could not verify Ollama server is running. Check 'brew services list' for status."
            fi
          fi


      - name: cargo test
        run: cargo test --all-features -p spnl -p spnl-cli
        
      - name: rustfmt
        run: cargo fmt --all -- --check

      - name: clippy
        run: cargo clippy --workspace --all-features --tests -- -D warnings
