name: playground

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# cancel any prior runs for this workflow and this PR (or branch)
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  
jobs:
  playground_build_and_test:
    name: playground
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./web/playground
    strategy:
      matrix:
        os:
          - ubuntu-latest
          # - windows-latest
          - macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: download rust-cache
        run: |
          mkdir ../../rust-cache-action && cd ../../rust-cache-action
          mkdir -p dist/save
          (cd dist/save && wget https://raw.githubusercontent.com/Swatinem/rust-cache/refs/heads/master/dist/save/index.js)
          mkdir -p dist/restore
          (cd dist/restore && wget https://raw.githubusercontent.com/Swatinem/rust-cache/refs/heads/master/dist/restore/index.js)
          wget https://raw.githubusercontent.com/Swatinem/rust-cache/refs/heads/master/action.yml
      - uses: ./rust-cache-action

      - name: setup
        run: npm ci
      - name: run tests
        run: npm test
      # - uses: actions/upload-artifact@v4
      #   if: ${{ !cancelled() }}
      #   with:
      #     name: playwright-report
      #     path: playwright-report/
      #     retention-days: 30
